### ISSUE TITLE
Time to switch to ESM?

### ISSUE THREAD

**Issue by jimmywarting** [tapjs/tap-mocha-reporter#69]
in order to update this ESM only dep
https://github.com/tapjs/tap-mocha-reporter/blob/5c8846fe3655aceb7ab104e5989b469b57601c00/package.json#L26

Then it would be grate if we made the switch and started to convert this mocha reporter to ESM-only, thoughts?

**Comment by isaacs** [comment]
No thanks.  Tap is used by many modules that are still using commonjs.  `require()` is fine.
