### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [tapjs/tap-mocha-reporter#70]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by isaacs** [comment]
You can email me at i@izs.me or probably ping me somehow in huntr.dev

**Comment by JamieSlome** [comment]
@isaacs - thanks for the ping! 👍 

You can view the report directly below, if that works for you?

https://huntr.dev/bounties/f5763687-4c09-403e-b956-ca9da1cdd19c/
